language: python
sudo: false

python:
  - "3.6.3"

install:
  - ./INSTALL.sh
  - source activate piret
  - export PATH="$HOME/build/mshakya/PyPiReT/thirdParty/miniconda/bin:$PATH"

script:
  - source activate piret
#  - export PATH="$HOME/build/mshakya/PyPiReT/thirdParty/miniconda/bin:$HOME/build/mshakya/PyPiReT/bin:$PATH"
  - sh tests/test_pipeline_linux.sh 
  - pytest --cov=./

after_success:
  - codecov