language: python
sudo: false

python:
  - "3.6.6"

services:
  - docker

script:
  - docker pull migun/piret:dev-latest
  - docker run -d -p 127.0.0.1:80:4567 migun/piret /bin/sh -c "samtools --help;"
  - ci_env="bash <(curl -s https://codecov.io/env)"
  - ci_post_cov="bash <(curl -s https://codecov.io/bash) -t $token"
  - docker run -t piret_test /bin/bash -c "$ci_env; source activate piret_env; cd /piret; pytest --cov=piret --cov-report=xml tests/ ;$ci_post_cov"
